name: expense_tracker_flutter
description: Monex Finance — smart expense tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.7.0
  shared_preferences: ^2.3.0
  go_router: ^17.1.0
  flutter_secure_storage: ^10.0.0
  google_fonts: ^8.0.2
  sqflite: ^2.3.3
  path: ^1.9.0
  connectivity_plus: ^7.0.0
  crypto: ^3.0.3
  adaptive_platform_ui: ^0.1.103
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^28.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/background.webp
    - assets/images/backdrop_wallets/
    - assets/icons/
    - assets/icons/wallets/
    - assets/icons/wallets/wallet_transaction/
    - assets/icons/Income/Category/
    - "assets/icons/Income/Sub Category/Active income/"
    - "assets/icons/Income/Sub Category/Business/"
    - "assets/icons/Income/Sub Category/Investment/"
    - "assets/icons/Income/Sub Category/Side Hustle/"
    - assets/icons/expense/Category/
    - "assets/icons/expense/Sub category/Bills/"
    - "assets/icons/expense/Sub category/Education/"
    - "assets/icons/expense/Sub category/Entertainment/"
    - "assets/icons/expense/Sub category/Family and Friends/"
    - "assets/icons/expense/Sub category/Financial/"
    - "assets/icons/expense/Sub category/Food and Beverage/"
    - "assets/icons/expense/Sub category/Health/"
    - "assets/icons/expense/Sub category/Personal/"
    - "assets/icons/expense/Sub category/Pet/"
    - "assets/icons/expense/Sub category/Service and Maintenance/"
    - "assets/icons/expense/Sub category/Shop/"
    - "assets/icons/expense/Sub category/Transport/"
    - "assets/icons/expense/Sub category/vacation/"
